# Generated by Django 3.1.1 on 2020-11-27 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_requestcounter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestcounter',
            old_name='requestCount',
            new_name='requests',
        ),
    ]
